build:
  version: 2016-03-14
  steps:
    base:
      name: bbase
      dockerfile: Dockerfile.base
    deployment:
        name: ddeployer
        dockerfile: Dockerfile.deployment
        depends_on:
          - base
