build:
  version: 2016-03-14
  steps:
    base:
      name: babakgh_base
      dockerfile: Dockerfile.base
    deployment:
        name: babakgh_deployer
        dockerfile: Dockerfile.deployment
        depends_on:
          - base
