build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile.builder
      artifacts:
        - /go/src/github.com/shahriarb/build_sample/ha_build_sample
    deployment:
        name: deployer
        dockerfile: Dockerfile.deployment
        depends_on:
          - builder
