scheduler1: bundle exec rake test:work
scheduler2: bundle exec rake test:work
scheduler3: bundle exec rake test:work
scheduler4: bundle exec rake test:work
scheduler5: bundle exec rake test:work
scheduler6: bundle exec rake test:work
scheduler7: bundle exec rake test:work
scheduler8: bundle exec rake test:work
scheduler9: bundle exec rake test:work
scheduler10: bundle exec rake test:work
scheduler11: bundle exec rake test:work
scheduler12: bundle exec rake test:work
scheduler13: bundle exec rake test:work
scheduler14: bundle exec rake test:work
scheduler15: bundle exec rake test:work
scheduler16: bundle exec rake test:work
scheduler17: bundle exec rake test:work
scheduler18: bundle exec rake test:work
scheduler19: bundle exec rake test:work
scheduler20: bundle exec rake test:work
scheduler21: bundle exec rake test:work
scheduler22: bundle exec rake test:work
scheduler23: bundle exec rake test:work
scheduler24: bundle exec rake test:work
scheduler25: bundle exec rake test:work
scheduler26: bundle exec rake test:work
scheduler27: bundle exec rake test:work
scheduler28: bundle exec rake test:work
scheduler29: bundle exec rake test:work
scheduler30: bundle exec rake test:work
scheduler31: bundle exec rake test:work
scheduler32: bundle exec rake test:work
scheduler33: bundle exec rake test:work
scheduler34: bundle exec rake test:work
scheduler35: bundle exec rake test:work
scheduler36: bundle exec rake test:work
scheduler37: bundle exec rake test:work
scheduler38: bundle exec rake test:work
scheduler39: bundle exec rake test:work
scheduler40: bundle exec rake test:work
scheduler41: bundle exec rake test:work
scheduler42: bundle exec rake test:work
scheduler43: bundle exec rake test:work
scheduler44: bundle exec rake test:work
scheduler45: bundle exec rake test:work
scheduler46: bundle exec rake test:work
scheduler47: bundle exec rake test:work
scheduler48: bundle exec rake test:work
scheduler49: bundle exec rake test:work
scheduler50: bundle exec rake test:work
scheduler51: bundle exec rake test:work
scheduler52: bundle exec rake test:work
